main: cn.wode490390.nukkit.cachesupport.CacheSupport
name: "CacheSupport"
description: "Client blob cache support plugin for Nukkit"
author: "wode490390"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.0"]
load: STARTUP
